name        : lzo
version     : 2.09
release     : 3
source     :
    - http://www.oberhumer.com/opensource/lzo/download/lzo-2.09.tar.gz : f294a7ced313063c057c504257f437c8335c41bfeed23531ee4e6a2b87bcb34c
license     : GPL-2.0+
summary     : LZO compression library
description : |
    This is the LZO compression library, suitable for data de-/compression in real-time. This means it favors speed over compression ratio.
setup      : |
    %configure --enable-shared \
               --disable-static \
               --docdir=/usr/share/doc/lzo
build      : |
    %make
install    : |
    %make_install
