name       : lzo
version    : '2.10'
release    : 4
source     :
    - https://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz : c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
license    : GPL-2.0-or-later
component  : programming.library
summary    : LZO compression library
description: |
    This is the LZO compression library, suitable for data de-/compression in real-time. This means it favors speed over compression ratio.
setup      : |
    %configure --enable-shared \
               --disable-static \
               --docdir=/usr/share/doc/lzo \
               --with-pkgconfigdir=%libdir%/pkgconfig/
build      : |
    %make
install    : |
    %make_install
